# Generated by Django 2.0.4 on 2018-04-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='snippets.Language', verbose_name='Language'),
        ),
    ]
