# Generated by Django 3.2.13 on 2022-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_snippetfavorite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='snippetfavorite',
            constraint=models.UniqueConstraint(fields=('snippet', 'user'), name='user_and_snippet_uniq'),
        ),
    ]
