# Generated by Django 5.2.16 on 2026-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippetfavorite_user_and_snippet_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='snippets',
            field=models.ManyToManyField(related_name='labels', through='snippets.SnippetLabel', through_fields=('label', 'snippet'), to='snippets.snippet', verbose_name='Snippets'),
        ),
    ]
