# Generated by Django 5.2.17 on 2026-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0006_alter_label_snippets"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
