# Generated by Django 2.0.5 on 2018-05-03 07:09

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
