# Generated by Django 2.0.4 on 2018-05-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_user_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='role',
            field=models.CharField(choices=[('EDITOR', 'Editor'), ('CONTRIBUTOR', 'Contributor'), ('SUBSCRIBER', 'Subscriber')], default='SUBSCRIBER', max_length=31),
        ),
    ]
