# Generated by Django 5.2.16 on 2026-07-19 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_unique_users_in_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', through='teams.UserTeam', through_fields=('team', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
